import type { NewsArticle } from '@/types';

export const mockNewsArticles: NewsArticle[] = [
  {
    article_id: '1',
    title: 'Breaking News: Major Technology Breakthrough',
    description: 'Scientists have discovered a revolutionary new technology that could change the way we think about energy.',
    summary: 'A team of researchers announced today a breakthrough in renewable energy technology that could significantly reduce global dependence on fossil fuels.',
    content: 'Scientists at the National Energy Laboratory have developed a new type of solar panel that can generate electricity even in low light conditions. The technology, which combines advanced materials with quantum computing principles, has shown efficiency rates of up to 70% in preliminary tests—far exceeding the 20-25% efficiency of current commercial solar panels.',
    publishedAt: '2023-10-15T15:30:00Z',
    category: 'technology',
    source: 'https://example.com/tech-breakthrough',
    image_url: 'https://images.unsplash.com/photo-1631556097152-c39479bbfb93?auto=format&fit=crop&q=80&w=1000',
  },
  {
    article_id: '2',
    title: 'Global Markets React to Economic Policy Changes',
    description: 'Stock markets worldwide showed significant movement following announcements of new economic policies.',
    summary: 'Major financial indices experienced volatility today as central banks in several countries announced coordinated policy changes aimed at controlling inflation.',
    content: 'Global financial markets experienced significant fluctuations today following announcements from the Federal Reserve, European Central Bank, and Bank of Japan regarding new coordinated monetary policies. The Dow Jones Industrial Average fell by 2.3% in early trading before recovering to close down 0.8%.',
    publishedAt: '2023-10-14T12:45:00Z',
    category: 'business',
    source: 'https://example.com/markets-react',
    image_url: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&q=80&w=1000',
  },
  {
    article_id: '3',
    title: 'Health Researchers Find New Benefits of Mediterranean Diet',
    description: 'A new study reveals additional health benefits associated with following a Mediterranean diet.',
    summary: 'Researchers have discovered that a Mediterranean diet rich in olive oil, nuts, and fresh vegetables may have even more health benefits than previously understood.',
    content: 'A comprehensive ten-year study involving over 15,000 participants has revealed new benefits of the Mediterranean diet. The research, published in the Journal of Nutrition and Health, found that consistent adherence to a diet rich in olive oil, nuts, fresh vegetables, and lean proteins was associated with a 35% reduction in cardiovascular events.',
    publishedAt: '2023-10-13T09:20:00Z',
    category: 'health',
    source: 'https://example.com/mediterranean-diet',
    image_url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&q=80&w=1000',
  },
  {
    article_id: '4',
    title: 'New Mars Rover Discovers Signs of Ancient Water Systems',
    description: 'NASA\'s latest Mars rover has found evidence suggesting extensive water networks once existed on the red planet.',
    summary: 'The discovery provides new insights into Mars\' past habitability and offers clues about where future missions might search for evidence of ancient microbial life.',
    content: 'NASA scientists announced today that the Perseverance rover has discovered compelling evidence of an ancient interconnected river system in Mars\' Jezero Crater. The findings, based on high-resolution imagery and mineral analysis, suggest that liquid water flowed on the Martian surface for extended periods approximately 3.5 billion years ago.',
    publishedAt: '2023-10-12T14:15:00Z',
    category: 'science',
    source: 'https://example.com/mars-water',
    image_url: 'https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?auto=format&fit=crop&q=80&w=1000',
  },
  {
    article_id: '5',
    title: 'Major Sports League Announces Expansion Teams',
    description: 'The league has confirmed plans to add two new teams in the upcoming season, bringing the total to 32 teams.',
    summary: 'After months of speculation, league officials have announced franchise approvals for two new cities, with play scheduled to begin next season.',
    content: 'The National Basketball Association officially announced today that it has approved expansion franchises for Las Vegas and Seattle, bringing the league to 32 teams starting with the 2025-26 season. The expansion represents the NBA\'s first new teams since 2004 when the Charlotte Bobcats (now Hornets) joined the league.',
    publishedAt: '2023-10-11T18:30:00Z',
    category: 'sports',
    source: 'https://example.com/league-expansion',
    image_url: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&q=80&w=1000',
  },
  {
    article_id: '6',
    title: 'Award-Winning Film Director Announces New Project',
    description: 'The acclaimed director has revealed details about an upcoming historical drama set to begin production next year.',
    summary: 'The film will explore a little-known historical event from the early 20th century, featuring an ensemble cast of award-winning actors.',
    content: 'Academy Award-winning director Christopher Nolan announced today his next project will be an epic historical drama titled "The Silent Hour." The film will explore the little-known 1908 Tunguska event, when a massive explosion—believed to be caused by a meteor—devastated over 800 square miles of Siberian forest.',
    publishedAt: '2023-10-10T21:45:00Z',
    category: 'entertainment',
    source: 'https://example.com/director-project',
    image_url: 'https://images.unsplash.com/photo-1542204165-65bf26472b9b?auto=format&fit=crop&q=80&w=1000',
  },
];
